# Generated by Django 5.0.4 on 2024-04-24 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('text_description', models.CharField(max_length=4096)),
                ('image_description', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('online_date', models.DateTimeField(verbose_name='date put online')),
                ('stock_inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=512, null=True)),
                ('date_published', models.CharField(max_length=512, null=True)),
                ('ISBN', models.CharField(max_length=512, null=True)),
                ('authors', models.CharField(max_length=512, null=True)),
                ('merchandise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
