# Generated by Django 5.0.4 on 2024-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_deadorder_status_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningorder',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
