# Generated by Django 5.0.4 on 2024-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_runningorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadorder',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
