# Generated by Django 5.0.4 on 2024-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_deadorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='image_type',
            field=models.CharField(default='image/jpeg', max_length=64),
            preserve_default=False,
        ),
    ]
