# Generated by Django 5.0.4 on 2024-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merchandise_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningorder',
            name='status_finishing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
