# Generated by Django 5.0.4 on 2024-05-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_runningorder_status_finishing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningorder',
            name='status_finishing',
        ),
        migrations.AddField(
            model_name='runningorder',
            name='status_end',
            field=models.CharField(default='running', max_length=64),
        ),
        migrations.DeleteModel(
            name='DeadOrder',
        ),
    ]
