# Generated by Django 5.0.4 on 2024-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_runningorder_status_finishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningorder',
            name='status_incart',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
